### ISSUE TITLE
[Lotto] Revisit Lotto Pools, Adjust to make slightly more worthwhile

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#124]
Revisit the Lotto pools for underwhelming tickets, such as Fabled. Potentially add a pool of "good" gifts that will be drawn from once to make lackluster tickets more worthwhile.

**Comment by MrBlizzard** [comment]
The idea for RCrates is more or less to only give goodies/gifts, and not really much of monetary value. Kinda like loot crate of sorts, with an assortment of stuff inside. The goal then isn't really to give back actually money, but more money in the form of gifts.

Here is the config for it, if you have any ideas list them here, and we can approve them before editing the actual gift. https://pastebin.com/xwBfvRmN

Alternatively, if we want to add another section to Lottery, and have a lottery menu be an overall menu containing the RCrate menu, we could make more options there for other things, maybe like a money lottery game, or something similar.

**Comment by MrBlizzard** [comment]
Changes/Additions:
- Balanced chances on all crates
- Added Plant Badge
- Changed Normal Boss Spawn to Mega Boss Parties
- Added New Held Item Pack to several crates
- Added Random Mega Stone Gift to several crates
- Added Rare chance at Pixelmon Ritual Stones starting at Marvelous and up
- Added another pool to Marvelous RCrate, can get one more thing now
- Added a guaranteed chance at either a Micro or Gino converter in Fabled
- Added a rare chance at Sumo and Gladiator converters in Mythical
- Added a Low Tier Legend gift at a common chance in Mythical
- Changed the Random Legendary gift in Ultimate to a New Legendary Gift, giving only 5.x+ legends
- Several other small edits, like giving 2 egg packs instead of one, 5 Nature randomizers instead of 3, etc
