### ISSUE TITLE
[NPC Interactions] NPC Trader offering Rotom for Ditto Causes Crash

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#18]
On occasion, a player choosing to trade a Ditto for a Rotom through an NPC Trader will crash their entire Launcher.

**Comment by MrBlizzard** [comment]
Let me know if this still occurs post 6.3 update.

**Comment by MrBlizzard** [comment]
Seems to work fine now, tested in pre update as well and it was working fine.

**Comment by PhantomWolf42** [comment]
Tested in-game post 6.3.1

Custom-made NPC asked if I'd like to trade my Ditto for their rotom, i said yes, then nothing happened. Also had Viala test.

**Comment by MrBlizzard** [comment]
Ah, yes. 6.3.1 has that bug confirmed. Whenever testing for 6.3.1 with the mods a few days ago they actually reported that first, then i brought it up to the devs personally, in which case they found it as a bug and said it would be fixed in the next version. kinda cool actually.

This ticket is being closed as it isn't an issue anymore. If we find it's an issue in the future we can reopen in the future.
