### ISSUE TITLE
[Spawn] Npcs at spawn need Statues

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#34]
All NPCs need statues beside them, and they need to be uniform (all the same on 1-6). 

The statues can be changed to different things to match their new models, whoever takes the task can have the liberty of deciding which npc gets what

**Comment by PhantomWolf42** [comment]
/tppos -3107 73 614
 - Male Scientist
 - Menu: mymenu
 - Statue: Froakie Ordinary, Chespin Huge, Fennekin Small

  /tppos -3100 73 615
 - Female Scientist
 - Menu: vote
 - Statue: Shaymin Giant (on glowstone between NPCs)

  /tppos -3097 73 612
 - Rich Boy
 - menu: donationstore
 - Statue: Shaymin Giant (on glowstone between NPCs)

  /tppos -3100 73 625
 - Poke Maniac - Pika Boy
 - action: pokeballs
 - Statue: Voltorb s

  /tppos -3105 73 625
 - Poke Maniac Girl - Zangoose
 - action: pidgeotlady
 - Statue: Pidgeot

  /tppos -3114 70 641
 - Bug Maniac
 - action: rpguy
 - Statue: Gardevoir Pygmy (In front of endrod)

  /tppos -3092 70 641
 - Bug Maniac
 - action: rpguy
 - Statue: Ralts Ginormous (In front of endrod)

  /tppos -3102 65 657
 - Female Pokemon Breeder 1
 - action: warpnpc
 - Statue: Abra runt

  /tppos -3112 65 662
 - Rich boy
 - menu: auc
 - Statue: Shiny Celebi Giant (On edge of garden bed step to NPC's right)

  /tppos -3104 65 663
 - Policeman
 - menu: help
 - Statue: Skitty Giant (To the left of NPC)

  /tppos -3094 65 661
 - Male Scientist
 - menu: rankup
 - Statue: Shiny Braviary Pygmy (directly replace the Murkrow)

  /tppos -3094 65 663
 - Female Scientist
 - action: kitmaster
 - Statue: Shiny Meowth - Enormous (To the right of Kits NPC)

  /tppos -3103 65 692
 - Steve - Suit
 - action: events 
   unless otherwise specified
 - Statue: Shiny Mew (Above the step to Event Dude's right)

  /tppos -3078 65 666
 - Bug Catcher - Bug Catcher
 - menu: pokecollector
 - Statue: Scyther Pygmy (On top of the wool to NPC's right)

  /tppos -3082 65 662
 - Steve - Scottish
 - menu: jobs
 - Statue: Bibarel Pygmy (On wool to NPC's left)

  /tppos -3067 67 644
 - Poke Maniac Girl - Oshawott
 - action: catch
 - Statue: Oshawott Huge (Delete Vaporeon, place Oshawott on bench left of trapdoor)

  /tppos -3067 67 640
 - Poke Maniac - Rhydon
 - menu/action: unknown
 - Statue: Rhyperior Runt (In back corner of stall)

  /tppos -3061 67 640
 - Swimmer
 - Action/Menu unknown
 - Statue: Gyarados Microscopic (On benchtop to left of NPC)

  /tppos -3059 62 640
 - Poke Maniac - Honchkrow
 - menu/action: unknown
 - Statue: Honchkrow Runt Flying (One block up in air, replace smeargle location)

  /tppos -3051 66 705
 - Doctor NPC
 - Statue: Chansey Small (On Bench to NPC's right)

  /tppos -3007 59 742
 - Miner
 - menu: gemtrader
 - Statue: Shiny Lugia Runt (In cave hole to NPC's right)

  /tppos -3123 65 673
 - Blacksmith
 - menu/action: unknown
 - Statue: Shiny Phanpy Runt (Remove pot, place phanpy)

  /tppos -3131 65 673
 - Poke Maniac - Rhydon
 - menu/action: unknown
 - Statue: Runt Riolu (On counter to right of NPC)

  /tppos -3151 67 650
 - Rich Boy
 - menu: mcshop
 - Statue: Entei Small (Idle: 110. Sitting on counter to right of NPC)

  /tppos -3133 67 648
 - Rancher
 - menu: pixelshop
 - Statue: Pichu Enormous (replace pikachu)

  /tppos -3163 70 761 
 - Firebreather - Medieval Firebreather
 - menu: badgetrader
 - Statue: Hitmonchan Ordinary (Block directly right of NPC)

**Comment by PhantomWolf42** [comment]
Recommend checking through list and suggesting changes. Most were chosen based on their relevance to the NPCs function (ie Bulk Up moves on Braviary works with Rankup function, PayDay on Phanpy works for Tokenshop)

**Comment by MrBlizzard** [comment]
Instead of hitmonchan for badge trader, we could have a new fire type poke.
For swimmer, we could have a new water type poke
Kitmaster could have throh, or sawk instead of meowth.

**Comment by PhantomWolf42** [comment]
List updated.
Hitmonchan changed to Fletchinder
Meowth changed to Sawk
Gyarados changed to Finneon + Lumineon https://i.imgur.com/feIoYXk.png

**Comment by PhantomWolf42** [comment]
All statues placed on all pixels.
