### ISSUE TITLE
[Gyms] Gyms Basic

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#4]
Completion of the updated Gyms Basic sheet. 

Has currently been organized, commands for gifts needs to change to the appropriate commands corresponding with Gym Gifts. 

If there are any burning suggestions for ways to improve, post below and I will incorporate them.

**Comment by MrBlizzard** [comment]
Gyms basics is done. Should be simple. One double check should be enough to make sure all the names are correct, badges given, etc

https://pastebin.com/GejnZPPr

**Comment by PhantomWolf42** [comment]
- "Receive" misspelt in all except Water Gym
- Water to Grass gyms receive Cascade gifts, rather than intended gifts
- Water Gym doesn't pay a pdisguise? (message does not say it does)

Gyms from Fen onwards;
- Old gym basic format? ie. eco give 100, pdisguise command + physical badges, no /gifts, /pex user

**Comment by PhantomWolf42** [comment]
Currently editing to add character/references to the games.

**Comment by PhantomWolf42** [comment]
https://pastebin.com/UHaUH8Rj

Made some edits added Gym names, altered 2 gym leader identities. Needs checking.

**Comment by PhantomWolf42** [comment]
Re-edits: https://pastebin.com/SJ7mNV77

Made all server messages uniform
Applied gym leader name to NPC speech that was separated into lines
Changed Pokémon to Pokemon
Fixed and tested colours in /a
