### ISSUE TITLE
[Vote/Voteshop] Revamp voteshop, rethink vote reward

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#48]
Vote Rewards:
- [x] Possibly add gems to the vote rewards
- [x] Possibly better pokeballs, quick balls maybe
- [x] Maybe boost money and claimblocks a tad
- [x] Possible EXP bottles to help get natures gift

Vote Shop:
- [x] Lower Price of all normal pokes, remove some old useless ones
- [x] Lower Price of all shiny pokes, remove some old useless ones
- [x] Adding Reforged stuff to shiny/normal/legendary
- [x] Lower old legend prices
- [x] Add Spawn Collection Photo Pack
- [x] Lower prices of some stuff (possibly masterball)
- [x] Adding rare items (held items maybe)

Anymore additions/edits should be posted here. Please feel free to through anything out there!

**Comment by PhantomWolf42** [comment]
Voteshop:
- Possible option to purchase "random" legendary, paid directly to player. All could be equally chanced, or rigged. More expensive than random spawn legend, less than the good legends.
- Add purchaseable RCrates for heavy amounts of credits (with cooldown tied to all, not to each tier)
- Possibly Voodoo Totem Shiny Converter, or new 1/2 chance version for very steep price.

Vote Rewards:
- Add a rare chance for vote to spawn 2 legends randomly instead of 1.
- Potentially add rank-rewards to voting. VIP/Deity ranks get a 10% boost on current awards perhaps.
- Edit Mystery Gift to have small chance to give Random Shiny, if not already implemented.
- Add Poke Parties to voting milestones, ie 60/120 votes.
