### ISSUE TITLE
[Buycraft Shop] Updates/Changes Ideas

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#49]
Edits:
- Bundle the less sold shinies into a groups of it's evos. 
- Bundle held items into packs (EV Training Pack, Breeding Pack, etc)

Additions:
- Held Item pack (10 for 5$)
- Bundles of Breeding Packs (similar to what was in MMR shop)
- More pixelmon stuff, not a lot atm.

Anymore additions/edits should be posted here. Please feel free to through anything out there!

**Comment by PhantomWolf42** [comment]
With the popularity of the RCrates from the store we could offer a pack of 5 Shiny Converters, 1/5 chance for the same price as the Shiny Conversion. Players would have the option to buy one confirmed converter, or take a gamble on 5 1/5 chance ones. Player seem to be happy spending money on chance.

We could add other /giftplayer shop items, so players can purchase things on sale and save for a later date. For example, with the 100% Shiny converter, we could offer a /giftplayer option rather than an instant purchase in-game. They'd be able to save it for when they need it that way. Similarly, we could add a 100% ultra IV gift only obtainable from the shop to be used when the player sees fit.

**Comment by PhantomWolf42** [comment]
Also, the /pheal purchaseable item in the webstore needs editing to be /pokeheal.
https://server.buycraft.net/payments/18301237

**Comment by PhantomWolf42** [comment]
Like the Egg Bundles, could add bundles of Mysterious Balls, Ancient Mysterious Balls and Futuristic Mysterious Balls to Buycraft. Rather than getting eggs, players have to catch what they get.

**Comment by PhantomWolf42** [comment]
Shiny Sylveon should be added to the Shiny Eeveelution bundle.

**Comment by MrBlizzard** [comment]
Any other ideas?

**Comment by MrBlizzard** [comment]
Brainstorming complete, Issue #105 Made to organize exactly what needs to be done.
