### ISSUE TITLE
Warp Hunt?

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#76]
Do we want it? If so how do we wanna do the new one?

**Comment by PhantomWolf42** [comment]
Bringing hunt back would be useful for players hunting low-tier legends, such as the birds and perhaps some lower additions, such as the regi's, Manaphy, Phione etc.

The old style was pretty good, perhaps a bigger version to accommodate the extra legends that could be added?

**Comment by MrBlizzard** [comment]
Bigger would be good. Not sure it has to be the same old tree design, but something lending to that might be cool. Do we want to have someone separate to our current build team make this? Seems they will be tied up for a bit with gyms, then RC Dungeons.

**Comment by PhantomWolf42** [comment]
A build by one person in-particular, or a new build team?

**Comment by PhantomWolf42** [comment]
I like the idea of the Headmod method. There are a couple Headmods (Kayla and Mono) who I know are pretty adept builders and might benefit from being given a task like this with a few mods to help. It would also give the project a bit of a leader rather than just a mod or 2, meaning we can step back from it a little more and mainly just supervise. Would be good to get the Headmods involved in things more as well.
